/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as BiRouteImport } from './routes/bi'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CarteirasRouteImport } from './routes/carteiras'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ErrosRouteImport } from './routes/erros'
import { Route as FolhaRouteImport } from './routes/folha'
import { Route as GanttRouteImport } from './routes/gantt'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as ObrigacoesRouteImport } from './routes/obrigacoes'
import { Route as SstRouteImport } from './routes/sst'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as TreinamentosRouteImport } from './routes/treinamentos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as EmpresasIndexRouteImport } from './routes/empresas.index'
import { Route as EmpresasEmpresaIdRouteImport } from './routes/empresas.$empresaId'
import { Route as ApiChatgptConsultaRouteImport } from './routes/api/chatgpt/consulta'
import { Route as ApiChatgptOpenapiDotjsonRouteImport } from './routes/api/chatgpt/openapi[.]json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteirasRoute = CarteirasRouteImport.update({
  id: '/carteiras',
  path: '/carteiras',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrosRoute = ErrosRouteImport.update({
  id: '/erros',
  path: '/erros',
  getParentRoute: () => rootRouteImport,
} as any)
const FolhaRoute = FolhaRouteImport.update({
  id: '/folha',
  path: '/folha',
  getParentRoute: () => rootRouteImport,
} as any)
const GanttRoute = GanttRouteImport.update({
  id: '/gantt',
  path: '/gantt',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigacoesRoute = ObrigacoesRouteImport.update({
  id: '/obrigacoes',
  path: '/obrigacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SstRoute = SstRouteImport.update({
  id: '/sst',
  path: '/sst',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentosRoute = TreinamentosRouteImport.update({
  id: '/treinamentos',
  path: '/treinamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasIndexRoute = EmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasEmpresaIdRoute = EmpresasEmpresaIdRouteImport.update({
  id: '/empresas/$empresaId',
  path: '/empresas/$empresaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatgptConsultaRoute = ApiChatgptConsultaRouteImport.update({
  id: '/api/chatgpt/consulta',
  path: '/api/chatgpt/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatgptOpenapiDotjsonRoute =
  ApiChatgptOpenapiDotjsonRouteImport.update({
    id: '/api/chatgpt/openapi.json',
    path: '/api/chatgpt/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/assistente': typeof AssistenteRoute
  '/bi': typeof BiRoute
  '/calendario': typeof CalendarioRoute
  '/carteiras': typeof CarteirasRoute
  '/checklists': typeof ChecklistsRoute
  '/documentos': typeof DocumentosRoute
  '/erros': typeof ErrosRoute
  '/folha': typeof FolhaRoute
  '/gantt': typeof GanttRoute
  '/grupos': typeof GruposRoute
  '/integracoes': typeof IntegracoesRoute
  '/obrigacoes': typeof ObrigacoesRoute
  '/sst': typeof SstRoute
  '/tarefas': typeof TarefasRoute
  '/treinamentos': typeof TreinamentosRoute
  '/usuarios': typeof UsuariosRoute
  '/api/mcp': typeof ApiMcpRoute
  '/empresas/$empresaId': typeof EmpresasEmpresaIdRoute
  '/empresas/': typeof EmpresasIndexRoute
  '/api/chatgpt/consulta': typeof ApiChatgptConsultaRoute
  '/api/chatgpt/openapi.json': typeof ApiChatgptOpenapiDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/assistente': typeof AssistenteRoute
  '/bi': typeof BiRoute
  '/calendario': typeof CalendarioRoute
  '/carteiras': typeof CarteirasRoute
  '/checklists': typeof ChecklistsRoute
  '/documentos': typeof DocumentosRoute
  '/erros': typeof ErrosRoute
  '/folha': typeof FolhaRoute
  '/gantt': typeof GanttRoute
  '/grupos': typeof GruposRoute
  '/integracoes': typeof IntegracoesRoute
  '/obrigacoes': typeof ObrigacoesRoute
  '/sst': typeof SstRoute
  '/tarefas': typeof TarefasRoute
  '/treinamentos': typeof TreinamentosRoute
  '/usuarios': typeof UsuariosRoute
  '/api/mcp': typeof ApiMcpRoute
  '/empresas/$empresaId': typeof EmpresasEmpresaIdRoute
  '/empresas': typeof EmpresasIndexRoute
  '/api/chatgpt/consulta': typeof ApiChatgptConsultaRoute
  '/api/chatgpt/openapi.json': typeof ApiChatgptOpenapiDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/assistente': typeof AssistenteRoute
  '/bi': typeof BiRoute
  '/calendario': typeof CalendarioRoute
  '/carteiras': typeof CarteirasRoute
  '/checklists': typeof ChecklistsRoute
  '/documentos': typeof DocumentosRoute
  '/erros': typeof ErrosRoute
  '/folha': typeof FolhaRoute
  '/gantt': typeof GanttRoute
  '/grupos': typeof GruposRoute
  '/integracoes': typeof IntegracoesRoute
  '/obrigacoes': typeof ObrigacoesRoute
  '/sst': typeof SstRoute
  '/tarefas': typeof TarefasRoute
  '/treinamentos': typeof TreinamentosRoute
  '/usuarios': typeof UsuariosRoute
  '/api/mcp': typeof ApiMcpRoute
  '/empresas/$empresaId': typeof EmpresasEmpresaIdRoute
  '/empresas/': typeof EmpresasIndexRoute
  '/api/chatgpt/consulta': typeof ApiChatgptConsultaRoute
  '/api/chatgpt/openapi.json': typeof ApiChatgptOpenapiDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/assistente'
    | '/bi'
    | '/calendario'
    | '/carteiras'
    | '/checklists'
    | '/documentos'
    | '/erros'
    | '/folha'
    | '/gantt'
    | '/grupos'
    | '/integracoes'
    | '/obrigacoes'
    | '/sst'
    | '/tarefas'
    | '/treinamentos'
    | '/usuarios'
    | '/api/mcp'
    | '/empresas/$empresaId'
    | '/empresas/'
    | '/api/chatgpt/consulta'
    | '/api/chatgpt/openapi.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/assistente'
    | '/bi'
    | '/calendario'
    | '/carteiras'
    | '/checklists'
    | '/documentos'
    | '/erros'
    | '/folha'
    | '/gantt'
    | '/grupos'
    | '/integracoes'
    | '/obrigacoes'
    | '/sst'
    | '/tarefas'
    | '/treinamentos'
    | '/usuarios'
    | '/api/mcp'
    | '/empresas/$empresaId'
    | '/empresas'
    | '/api/chatgpt/consulta'
    | '/api/chatgpt/openapi.json'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/assistente'
    | '/bi'
    | '/calendario'
    | '/carteiras'
    | '/checklists'
    | '/documentos'
    | '/erros'
    | '/folha'
    | '/gantt'
    | '/grupos'
    | '/integracoes'
    | '/obrigacoes'
    | '/sst'
    | '/tarefas'
    | '/treinamentos'
    | '/usuarios'
    | '/api/mcp'
    | '/empresas/$empresaId'
    | '/empresas/'
    | '/api/chatgpt/consulta'
    | '/api/chatgpt/openapi.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AssistenteRoute: typeof AssistenteRoute
  BiRoute: typeof BiRoute
  CalendarioRoute: typeof CalendarioRoute
  CarteirasRoute: typeof CarteirasRoute
  ChecklistsRoute: typeof ChecklistsRoute
  DocumentosRoute: typeof DocumentosRoute
  ErrosRoute: typeof ErrosRoute
  FolhaRoute: typeof FolhaRoute
  GanttRoute: typeof GanttRoute
  GruposRoute: typeof GruposRoute
  IntegracoesRoute: typeof IntegracoesRoute
  ObrigacoesRoute: typeof ObrigacoesRoute
  SstRoute: typeof SstRoute
  TarefasRoute: typeof TarefasRoute
  TreinamentosRoute: typeof TreinamentosRoute
  UsuariosRoute: typeof UsuariosRoute
  ApiMcpRoute: typeof ApiMcpRoute
  EmpresasEmpresaIdRoute: typeof EmpresasEmpresaIdRoute
  EmpresasIndexRoute: typeof EmpresasIndexRoute
  ApiChatgptConsultaRoute: typeof ApiChatgptConsultaRoute
  ApiChatgptOpenapiDotjsonRoute: typeof ApiChatgptOpenapiDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteiras': {
      id: '/carteiras'
      path: '/carteiras'
      fullPath: '/carteiras'
      preLoaderRoute: typeof CarteirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erros': {
      id: '/erros'
      path: '/erros'
      fullPath: '/erros'
      preLoaderRoute: typeof ErrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folha': {
      id: '/folha'
      path: '/folha'
      fullPath: '/folha'
      preLoaderRoute: typeof FolhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gantt': {
      id: '/gantt'
      path: '/gantt'
      fullPath: '/gantt'
      preLoaderRoute: typeof GanttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigacoes': {
      id: '/obrigacoes'
      path: '/obrigacoes'
      fullPath: '/obrigacoes'
      preLoaderRoute: typeof ObrigacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sst': {
      id: '/sst'
      path: '/sst'
      fullPath: '/sst'
      preLoaderRoute: typeof SstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamentos': {
      id: '/treinamentos'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof TreinamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/': {
      id: '/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof EmpresasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/$empresaId': {
      id: '/empresas/$empresaId'
      path: '/empresas/$empresaId'
      fullPath: '/empresas/$empresaId'
      preLoaderRoute: typeof EmpresasEmpresaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chatgpt/consulta': {
      id: '/api/chatgpt/consulta'
      path: '/api/chatgpt/consulta'
      fullPath: '/api/chatgpt/consulta'
      preLoaderRoute: typeof ApiChatgptConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chatgpt/openapi.json': {
      id: '/api/chatgpt/openapi.json'
      path: '/api/chatgpt/openapi.json'
      fullPath: '/api/chatgpt/openapi.json'
      preLoaderRoute: typeof ApiChatgptOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AssistenteRoute: AssistenteRoute,
  BiRoute: BiRoute,
  CalendarioRoute: CalendarioRoute,
  CarteirasRoute: CarteirasRoute,
  ChecklistsRoute: ChecklistsRoute,
  DocumentosRoute: DocumentosRoute,
  ErrosRoute: ErrosRoute,
  FolhaRoute: FolhaRoute,
  GanttRoute: GanttRoute,
  GruposRoute: GruposRoute,
  IntegracoesRoute: IntegracoesRoute,
  ObrigacoesRoute: ObrigacoesRoute,
  SstRoute: SstRoute,
  TarefasRoute: TarefasRoute,
  TreinamentosRoute: TreinamentosRoute,
  UsuariosRoute: UsuariosRoute,
  ApiMcpRoute: ApiMcpRoute,
  EmpresasEmpresaIdRoute: EmpresasEmpresaIdRoute,
  EmpresasIndexRoute: EmpresasIndexRoute,
  ApiChatgptConsultaRoute: ApiChatgptConsultaRoute,
  ApiChatgptOpenapiDotjsonRoute: ApiChatgptOpenapiDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
